use std::io::Write;

use crate::error::Error;
use crate::symbols::FunctionSymbol;

const HEADER: &str = "\
// This file has been generated by zoltan (https://github.com/jac3km4/zoltan)
";

pub fn write_c_header<W: Write>(symbols: &[FunctionSymbol], mut out: W) -> Result<(), Error> {
    writeln!(out, "{}", HEADER)?;
    for symbol in symbols {
        writeln!(
            out,
            "#define {}_ADDR 0x{:X}",
            symbol.name().to_uppercase(),
            symbol.addr()
        )?;
    }

    Ok(())
}

pub fn write_rust_header<W: Write>(symbols: &[FunctionSymbol], mut out: W) -> Result<(), Error> {
    writeln!(out, "{}", HEADER)?;
    for symbol in symbols {
        writeln!(
            out,
            "const {}_ADDR: usize = 0x{:X};",
            symbol.name().to_uppercase(),
            symbol.addr()
        )?;
    }

    Ok(())
}
